
import { Factor } from "@/types/questionnaire";

// Questionário psicossocial inspirado no COPSOQ III, adaptado e expandido (~120 perguntas)
export const questionnaireData: Factor[] = [
  {
    id: "demands_quantitative",
    title: "Demandas Quantitativas",
    description: "Carga de trabalho, ritmo e volume de tarefas.",
    questions: [
      { id: "dq1", text: "Preciso trabalhar em ritmo acelerado para cumprir minhas tarefas." },
      { id: "dq2", text: "Recebo mais tarefas do que consigo realizar no tempo disponível." },
      { id: "dq3", text: "Tenho prazos curtos para entregar meu trabalho." },
      { id: "dq4", text: "Frequentemente preciso fazer horas extras para dar conta do serviço." },
      { id: "dq5", text: "Meu trabalho exige atenção constante ao tempo todo." },
      { id: "dq6", text: "Sinto que o volume de trabalho é excessivo." },
      { id: "dq7", text: "Tenho pouco tempo para pausas durante o expediente." },
      { id: "dq8", text: "Preciso lidar com várias tarefas ao mesmo tempo." },
      { id: "dq9", text: "O ritmo de trabalho é intenso na maior parte do tempo." },
      { id: "dq10", text: "Recebo demandas inesperadas com frequência." },
    ]
  },
  {
    id: "demands_cognitive",
    title: "Demandas Cognitivas",
    description: "Exigências de atenção, memória e tomada de decisão.",
    questions: [
      { id: "dc1", text: "Preciso memorizar muitas informações para realizar meu trabalho." },
      { id: "dc2", text: "Meu trabalho exige que eu tome decisões difíceis." },
      { id: "dc3", text: "Preciso aprender coisas novas frequentemente." },
      { id: "dc4", text: "Enfrento situações inesperadas que exigem solução rápida." },
      { id: "dc5", text: "Preciso analisar dados ou informações complexas." },
      { id: "dc6", text: "Meu trabalho exige concentração intensa por longos períodos." },
      { id: "dc7", text: "Preciso lidar com informações contraditórias ou incompletas." },
      { id: "dc8", text: "Sou responsável por planejar atividades detalhadas." },
      { id: "dc9", text: "Preciso revisar frequentemente o que foi feito para evitar erros." },
      { id: "dc10", text: "Tenho autonomia para propor soluções para problemas do trabalho." },
    ],
  },
  {
    id: "demands_emotional",
    title: "Demandas Emocionais",
    description: "Exigências emocionais e contato com situações difíceis.",
    questions: [
      { id: "de1", text: "Preciso lidar com pessoas em situações de conflito ou estresse." },
      { id: "de2", text: "Meu trabalho exige que eu mantenha a calma mesmo sob pressão." },
      { id: "de3", text: "Preciso esconder meus sentimentos para manter o profissionalismo." },
      { id: "de4", text: "Frequentemente sou exposto a situações emocionalmente desgastantes." },
      { id: "de5", text: "Preciso apoiar colegas ou clientes em momentos difíceis." },
      { id: "de6", text: "Sinto que o trabalho afeta meu equilíbrio emocional." },
      { id: "de7", text: "Preciso lidar com reclamações ou críticas constantes." },
      { id: "de8", text: "Tenho que ser empático mesmo quando não concordo com a situação." },
      { id: "de9", text: "Preciso controlar emoções negativas durante o trabalho." },
      { id: "de10", text: "Meu trabalho exige envolvimento emocional frequente." },
    ],
  },
  {
    id: "influence",
    title: "Influência e Autonomia",
    description: "Capacidade de decidir e influenciar o próprio trabalho.",
    questions: [
      { id: "inf1", text: "Tenho autonomia para decidir como executar minhas tarefas." },
      { id: "inf2", text: "Posso sugerir mudanças na forma de realizar o trabalho." },
      { id: "inf3", text: "Tenho influência sobre decisões importantes do setor." },
      { id: "inf4", text: "Posso escolher a ordem das atividades que realizo." },
      { id: "inf5", text: "Tenho liberdade para propor melhorias no ambiente de trabalho." },
      { id: "inf6", text: "Sou ouvido quando apresento sugestões para a equipe." },
      { id: "inf7", text: "Posso decidir quando fazer pausas durante o expediente." },
      { id: "inf8", text: "Tenho flexibilidade para ajustar meu horário de trabalho." },
      { id: "inf9", text: "Participo de reuniões onde posso expressar minha opinião." },
      { id: "inf10", text: "Tenho autonomia para resolver problemas do dia a dia." },
    ],
  },
  {
    id: "development",
    title: "Desenvolvimento e Aprendizagem",
    description: "Oportunidades de crescimento e aprendizado no trabalho.",
    questions: [
      { id: "dev1", text: "Tenho oportunidades de aprender coisas novas no trabalho." },
      { id: "dev2", text: "Meu trabalho permite desenvolver novas habilidades." },
      { id: "dev3", text: "Recebo feedback construtivo sobre meu desempenho." },
      { id: "dev4", text: "Tenho acesso a treinamentos ou capacitações." },
      { id: "dev5", text: "Sou incentivado a buscar aperfeiçoamento profissional." },
      { id: "dev6", text: "Tenho oportunidades de crescimento na carreira." },
      { id: "dev7", text: "Posso participar de projetos desafiadores." },
      { id: "dev8", text: "Recebo apoio para desenvolver minhas competências." },
      { id: "dev9", text: "Tenho clareza sobre as possibilidades de promoção." },
      { id: "dev10", text: "Meu trabalho contribui para meu desenvolvimento pessoal." },
    ],
  },
  {
    id: "predictability",
    title: "Previsibilidade e Informação",
    description: "Acesso a informações e previsibilidade das mudanças.",
    questions: [
      { id: "pre1", text: "Recebo informações antecipadas sobre mudanças no trabalho." },
      { id: "pre2", text: "Sou informado sobre decisões que afetam minha rotina." },
      { id: "pre3", text: "Tenho clareza sobre as metas do setor." },
      { id: "pre4", text: "Recebo orientações claras sobre minhas tarefas." },
      { id: "pre5", text: "Mudanças importantes são comunicadas com antecedência." },
      { id: "pre6", text: "Sei o que esperar do meu trabalho nos próximos meses." },
      { id: "pre7", text: "Tenho acesso fácil às informações necessárias para o trabalho." },
      { id: "pre8", text: "Recebo feedback sobre mudanças de processos." },
      { id: "pre9", text: "Sou avisado sobre alterações de horário ou escala." },
      { id: "pre10", text: "Tenho previsibilidade sobre minha carga de trabalho." },
    ],
  },
  {
    id: "recognition",
    title: "Reconhecimento e Valorização",
    description: "Reconhecimento pelo trabalho realizado.",
    questions: [
      { id: "rec1", text: "Recebo reconhecimento pelo meu desempenho." },
      { id: "rec2", text: "Meu trabalho é valorizado pela liderança." },
      { id: "rec3", text: "Recebo elogios quando faço um bom trabalho." },
      { id: "rec4", text: "Sou recompensado por resultados positivos." },
      { id: "rec5", text: "Sinto que minha dedicação é percebida pela equipe." },
      { id: "rec6", text: "Tenho oportunidades de mostrar minhas conquistas." },
      { id: "rec7", text: "Recebo incentivos para continuar me dedicando." },
      { id: "rec8", text: "Sou reconhecido publicamente por bons resultados." },
      { id: "rec9", text: "Meus esforços são levados em consideração nas avaliações." },
      { id: "rec10", text: "Sinto que faço diferença no ambiente de trabalho." },
    ],
  },
  {
    id: "support_colleagues",
    title: "Apoio dos Colegas",
    description: "Ajuda, colaboração e suporte entre colegas.",
    questions: [
      { id: "sc1", text: "Posso contar com meus colegas quando preciso de ajuda." },
      { id: "sc2", text: "Meus colegas colaboram para o bom andamento do trabalho." },
      { id: "sc3", text: "Recebo apoio emocional dos colegas em momentos difíceis." },
      { id: "sc4", text: "Os colegas compartilham informações importantes." },
      { id: "sc5", text: "Sinto que faço parte de uma equipe unida." },
      { id: "sc6", text: "Meus colegas respeitam minhas opiniões." },
      { id: "sc7", text: "Há espírito de cooperação entre os colegas." },
      { id: "sc8", text: "Posso pedir conselhos aos colegas sem receio." },
      { id: "sc9", text: "Os colegas ajudam a resolver conflitos no setor." },
      { id: "sc10", text: "Recebo apoio prático dos colegas no dia a dia." },
    ],
  },
  {
    id: "support_supervisor",
    title: "Apoio da Liderança",
    description: "Ajuda, orientação e suporte do superior imediato.",
    questions: [
      { id: "ss1", text: "Posso contar com meu superior imediato quando preciso de orientação." },
      { id: "ss2", text: "Recebo apoio do meu gestor em situações difíceis." },
      { id: "ss3", text: "Meu superior está disponível para esclarecer dúvidas." },
      { id: "ss4", text: "Recebo feedback construtivo da liderança." },
      { id: "ss5", text: "Meu gestor incentiva o desenvolvimento da equipe." },
      { id: "ss6", text: "A liderança reconhece meus esforços." },
      { id: "ss7", text: "Posso conversar abertamente com meu superior sobre problemas do trabalho." },
      { id: "ss8", text: "Meu gestor apoia a resolução de conflitos na equipe." },
      { id: "ss9", text: "Recebo orientações claras da liderança." },
      { id: "ss10", text: "Meu superior demonstra interesse pelo bem-estar da equipe." },
    ],
  },
  {
    id: "leadership_quality",
    title: "Qualidade da Liderança",
    description: "Planejamento, justiça e foco no bem-estar dos funcionários.",
    questions: [
      { id: "ql1", text: "A liderança planeja bem as atividades do setor." },
      { id: "ql2", text: "Os gestores resolvem conflitos de forma justa." },
      { id: "ql3", text: "A liderança prioriza o bem-estar dos funcionários." },
      { id: "ql4", text: "Os líderes comunicam claramente as expectativas." },
      { id: "ql5", text: "A liderança é acessível para ouvir sugestões." },
      { id: "ql6", text: "Os gestores promovem um ambiente de respeito." },
      { id: "ql7", text: "A liderança incentiva a participação dos funcionários." },
      { id: "ql8", text: "Os líderes reconhecem o esforço coletivo da equipe." },
      { id: "ql9", text: "A liderança é transparente nas decisões." },
      { id: "ql10", text: "Os gestores apoiam o desenvolvimento profissional dos funcionários." },
    ],
  },
  {
    id: "teamwork",
    title: "Trabalho em Equipe",
    description: "Colaboração, integração e funcionamento do grupo.",
    questions: [
      { id: "tw1", text: "O trabalho em equipe é valorizado na empresa." },
      { id: "tw2", text: "Os membros da equipe colaboram entre si." },
      { id: "tw3", text: "Há integração entre diferentes áreas da empresa." },
      { id: "tw4", text: "A equipe compartilha objetivos comuns." },
      { id: "tw5", text: "Os resultados do grupo são reconhecidos." },
      { id: "tw6", text: "A equipe resolve problemas de forma conjunta." },
      { id: "tw7", text: "Há respeito mútuo entre os membros da equipe." },
      { id: "tw8", text: "A equipe se apoia em momentos de dificuldade." },
      { id: "tw9", text: "Os membros da equipe compartilham conhecimentos." },
      { id: "tw10", text: "A equipe celebra conquistas coletivas." },
    ],
  },
  {
    id: "organizational_justice",
    title: "Justiça Organizacional",
    description: "Equidade, transparência e justiça nas decisões.",
    questions: [
      { id: "oj1", text: "As decisões na empresa são tomadas de forma justa." },
      { id: "oj2", text: "Os funcionários são tratados com equidade." },
      { id: "oj3", text: "Os critérios de promoção são transparentes." },
      { id: "oj4", text: "A empresa respeita os direitos dos trabalhadores." },
      { id: "oj5", text: "As regras são aplicadas igualmente a todos." },
      { id: "oj6", text: "Os funcionários podem recorrer de decisões injustas." },
      { id: "oj7", text: "A empresa valoriza a diversidade e inclusão." },
      { id: "oj8", text: "Os processos seletivos são transparentes." },
      { id: "oj9", text: "A empresa combate práticas discriminatórias." },
      { id: "oj10", text: "Os funcionários participam das decisões importantes." },
    ],
  },
  {
    id: "vertical_trust",
    title: "Confiança Vertical",
    description: "Relação de confiança entre funcionários e liderança.",
    questions: [
      { id: "vt1", text: "Confio nas decisões tomadas pela liderança." },
      { id: "vt2", text: "A liderança confia nos funcionários para executar suas tarefas." },
      { id: "vt3", text: "Sinto que posso ser honesto com meus gestores." },
      { id: "vt4", text: "A liderança cumpre o que promete." },
      { id: "vt5", text: "Os gestores confiam na capacidade da equipe." },
      { id: "vt6", text: "A liderança compartilha informações relevantes." },
      { id: "vt7", text: "Os gestores apoiam a autonomia dos funcionários." },
      { id: "vt8", text: "A liderança incentiva a comunicação aberta." },
      { id: "vt9", text: "Os gestores reconhecem os erros e buscam soluções." },
      { id: "vt10", text: "A confiança é um valor presente na empresa." },
    ],
  },
  {
    id: "rewards",
    title: "Recompensas e Benefícios",
    description: "Satisfação com salário, benefícios e reconhecimento.",
    questions: [
      { id: "rw1", text: "Estou satisfeito com meu salário atual." },
      { id: "rw2", text: "Os benefícios oferecidos pela empresa atendem minhas necessidades." },
      { id: "rw3", text: "Recebo recompensas proporcionais ao meu desempenho." },
      { id: "rw4", text: "Tenho oportunidades de receber bônus ou prêmios." },
      { id: "rw5", text: "O reconhecimento financeiro é justo na empresa." },
      { id: "rw6", text: "Os critérios para aumento salarial são claros." },
      { id: "rw7", text: "Estou satisfeito com as oportunidades de promoção." },
      { id: "rw8", text: "A empresa valoriza o esforço dos funcionários." },
      { id: "rw9", text: "Recebo benefícios compatíveis com o mercado." },
      { id: "rw10", text: "O reconhecimento não financeiro é valorizado na empresa." },
    ],
  },
  {
    id: "job_insecurity",
    title: "Insegurança no Trabalho",
    description: "Medo de perder o emprego ou de mudanças negativas.",
    questions: [
      { id: "ji1", text: "Tenho receio de perder meu emprego." },
      { id: "ji2", text: "Mudanças na empresa me deixam inseguro quanto ao futuro." },
      { id: "ji3", text: "Sinto que meu cargo pode ser extinto a qualquer momento." },
      { id: "ji4", text: "Tenho medo de ser demitido sem justificativa." },
      { id: "ji5", text: "Mudanças de gestão aumentam minha insegurança." },
      { id: "ji6", text: "Sinto que minha estabilidade no emprego está ameaçada." },
      { id: "ji7", text: "Tenho dúvidas sobre a continuidade do meu setor." },
      { id: "ji8", text: "A empresa passa por constantes reestruturações." },
      { id: "ji9", text: "Tenho medo de perder benefícios em mudanças." },
      { id: "ji10", text: "A instabilidade econômica afeta minha segurança no trabalho." },
    ],
  },
  {
    id: "stress_symptoms",
    title: "Sintomas de Estresse",
    description: "Sinais físicos e emocionais de estresse relacionado ao trabalho.",
    questions: [
      { id: "ss1", text: "Sinto-me frequentemente estressado devido ao trabalho." },
      { id: "ss2", text: "Tenho dificuldade para relaxar após o expediente." },
      { id: "ss3", text: "Sinto cansaço físico ou mental constante." },
      { id: "ss4", text: "Tenho insônia ou sono de má qualidade por causa do trabalho." },
      { id: "ss5", text: "Sinto dores de cabeça relacionadas ao estresse." },
      { id: "ss6", text: "Tenho sintomas físicos como dor muscular ou tensão." },
      { id: "ss7", text: "Sinto irritação ou impaciência frequente." },
      { id: "ss8", text: "Tenho dificuldade de concentração devido ao estresse." },
      { id: "ss9", text: "Sinto ansiedade relacionada ao ambiente de trabalho." },
      { id: "ss10", text: "O estresse do trabalho afeta minha vida pessoal." },
    ],
  },
  {
    id: "job_satisfaction",
    title: "Satisfação no Trabalho",
    description: "Satisfação geral e recomendação do local de trabalho.",
    questions: [
      { id: "js1", text: "Estou satisfeito com meu trabalho em geral." },
      { id: "js2", text: "Recomendaria meu local de trabalho para outras pessoas." },
      { id: "js3", text: "Sinto orgulho de fazer parte da empresa." },
      { id: "js4", text: "Estou motivado para realizar minhas atividades." },
      { id: "js5", text: "Sinto que meu trabalho tem propósito." },
      { id: "js6", text: "Estou satisfeito com o ambiente físico de trabalho." },
      { id: "js7", text: "Tenho equilíbrio entre vida pessoal e profissional." },
      { id: "js8", text: "Sinto que sou respeitado no ambiente de trabalho." },
      { id: "js9", text: "Tenho satisfação com as relações interpessoais no trabalho." },
      { id: "js10", text: "Estou satisfeito com as oportunidades de crescimento." },
    ],
  },
  {
    id: "work_family_conflict",
    title: "Conflito Trabalho-Família",
    description: "Interferência do trabalho nas responsabilidades familiares.",
    questions: [
      { id: "wfc1", text: "Meu trabalho interfere nas minhas responsabilidades familiares." },
      { id: "wfc2", text: "Tenho dificuldade para conciliar trabalho e família." },
      { id: "wfc3", text: "O tempo dedicado ao trabalho prejudica minha vida pessoal." },
      { id: "wfc4", text: "Sinto que não tenho tempo suficiente para a família." },
      { id: "wfc5", text: "O estresse do trabalho afeta meu convívio familiar." },
      { id: "wfc6", text: "Preciso abrir mão de compromissos familiares por causa do trabalho." },
      { id: "wfc7", text: "Tenho dificuldade para participar de eventos familiares." },
      { id: "wfc8", text: "O trabalho exige disponibilidade fora do horário comercial." },
      { id: "wfc9", text: "Sinto culpa por não dedicar mais tempo à família." },
      { id: "wfc10", text: "Minha família reclama da minha ausência devido ao trabalho." },
    ],
  },
  {
    id: "bullying",
    title: "Assédio Moral",
    description: "Vivência de situações de assédio moral no trabalho.",
    questions: [
      { id: "bul1", text: "Já fui alvo de comentários ofensivos no trabalho." },
      { id: "bul2", text: "Sofri humilhações ou constrangimentos por parte de colegas ou chefia." },
      { id: "bul3", text: "Fui excluído de atividades ou decisões importantes." },
      { id: "bul4", text: "Recebi críticas injustas ou em público." },
      { id: "bul5", text: "Fui alvo de boatos ou fofocas no ambiente de trabalho." },
      { id: "bul6", text: "Senti que minha reputação foi prejudicada por terceiros." },
      { id: "bul7", text: "Fui pressionado a pedir demissão." },
      { id: "bul8", text: "Fui ameaçado de perder o emprego sem motivo justo." },
      { id: "bul9", text: "Fui alvo de discriminação por características pessoais." },
      { id: "bul10", text: "Já presenciei colegas sendo assediados moralmente." },
    ],
  },
  {
    id: "physical_violence",
    title: "Violência Física",
    description: "Vivência de situações de violência física no trabalho.",
    questions: [
      { id: "pv1", text: "Já fui vítima de agressão física no ambiente de trabalho." },
      { id: "pv2", text: "Presenciei situações de violência física entre colegas." },
      { id: "pv3", text: "Fui ameaçado fisicamente por alguém do trabalho." },
      { id: "pv4", text: "Já precisei intervir em brigas físicas no trabalho." },
      { id: "pv5", text: "Sinto medo de sofrer agressão física no trabalho." },
    ],
  },
  {
    id: "sexual_harassment",
    title: "Assédio Sexual",
    description: "Vivência de situações de assédio sexual no trabalho.",
    questions: [
      { id: "sh1", text: "Já recebi propostas ou insinuações de cunho sexual no trabalho." },
      { id: "sh2", text: "Fui alvo de comentários ou piadas sexuais no ambiente de trabalho." },
      { id: "sh3", text: "Presenciei situações de assédio sexual envolvendo colegas." },
      { id: "sh4", text: "Fui tocado sem consentimento no ambiente de trabalho." },
	  { id: "sh5", text: "Senti desconforto por olhares ou gestos inadequados no trabalho." }
    ]
  }
];

