-- Tabela de afastamentos
create table if not exists public.afastamentos (
  id bigint generated by default as identity primary key,
  id_funcionario bigint references public.funcionario(id_sst) on delete cascade,
  data_inicio date not null,
  data_fim date,
  motivo text not null,
  tipo text, -- doença, acidente, licença, etc.
  cid text,
  observacao text,
  arquivo_atestado text, -- URL do arquivo
  medico text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Tabela de restrições médicas
create table if not exists public.restricoes_medicas (
  id bigint generated by default as identity primary key,
  id_funcionario bigint references public.funcionario(id_sst) on delete cascade,
  descricao text not null,
  data_inicio date not null,
  data_fim date,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Permissões básicas
alter table public.afastamentos enable row level security;
create policy "Allow insert for all" on public.afastamentos for insert with check (true);
create policy "Allow select for all" on public.afastamentos for select using (true);
alter table public.restricoes_medicas enable row level security;
create policy "Allow insert for all" on public.restricoes_medicas for insert with check (true);
create policy "Allow select for all" on public.restricoes_medicas for select using (true);
