-- Tabela de auditorias
create table if not exists public.auditorias (
  id bigint generated by default as identity primary key,
  tipo text not null, -- interna, externa, periódica, etc.
  data date not null,
  auditor text,
  setor text,
  status text, -- planejada, em andamento, concluída
  observacao text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Tabela de checklist de auditoria
create table if not exists public.auditoria_checklist (
  id bigint generated by default as identity primary key,
  id_auditoria bigint references public.auditorias(id) on delete cascade,
  nr text, -- NR relacionada
  item text, -- item da NR
  conforme boolean,
  observacao text,
  evidencia_url text, -- arquivo de evidência
  created_at timestamp with time zone default timezone('utc', now())
);

-- Tabela de não conformidades
create table if not exists public.auditoria_nao_conformidade (
  id bigint generated by default as identity primary key,
  id_auditoria bigint references public.auditorias(id) on delete cascade,
  descricao text not null,
  plano_acao text,
  responsavel text,
  prazo date,
  status text, -- pendente, em andamento, concluída
  created_at timestamp with time zone default timezone('utc', now())
);

-- Permissões básicas
alter table public.auditorias enable row level security;
create policy "Allow insert for all" on public.auditorias for insert with check (true);
create policy "Allow select for all" on public.auditorias for select using (true);
alter table public.auditoria_checklist enable row level security;
create policy "Allow insert for all" on public.auditoria_checklist for insert with check (true);
create policy "Allow select for all" on public.auditoria_checklist for select using (true);
alter table public.auditoria_nao_conformidade enable row level security;
create policy "Allow insert for all" on public.auditoria_nao_conformidade for insert with check (true);
create policy "Allow select for all" on public.auditoria_nao_conformidade for select using (true);
