-- Exemplo de setores
insert into public.sectors (nome) values
  ('Produção'),
  ('Administrativo'),
  ('Manutenção'),
  ('Logística');

-- Exemplo de agentes causadores
insert into public.occupational_risk_agents (nome) values
  ('Máquina industrial'),
  ('Produto químico'),
  ('Ferramenta manual'),
  ('Veículo');
create table if not exists public.cids (
  id bigint generated by default as identity primary key,
  capitulo text,         -- Ex: "I"
  grupo text,            -- Ex: "A00-A09"
  categoria text,        -- Ex: "A00"
  descricao text not null,        -- Ex: "Cólera"
  cod_cat text,          -- Ex: "A00"
  cod_grupo text,        -- Ex: "A00-A09"
  codigo text            -- Campo alternativo para compatibilidade (pode ser igual a categoria ou cod_cat)
);

alter table public.cids enable row level security;
drop policy if exists "Allow insert for all" on public.cids;
create policy "Allow insert for all" on public.cids for insert with check (true);
drop policy if exists "Allow select for all" on public.cids;
create policy "Allow select for all" on public.cids for select using (true);


-- Inserção dos capítulos do CID-10
insert into public.cids (capitulo, grupo, categoria, descricao, cod_cat, cod_grupo, codigo) values
  ('I', 'A00-B99', 'A00', 'Capítulo I - Algumas doenças infecciosas e parasitárias', 'A00', 'A00-B99', 'A00'),
  ('II', 'C00-D48', 'C00', 'Capítulo II - Neoplasias [tumores]', 'C00', 'C00-D48', 'C00'),
  ('III', 'D50-D89', 'D50', 'Capítulo III - Doenças do sangue e dos órgãos hematopoéticos e alguns transtornos imunitários', 'D50', 'D50-D89', 'D50'),
  ('IV', 'E00-E90', 'E00', 'Capítulo IV - Doenças endócrinas, nutricionais e metabólicas', 'E00', 'E00-E90', 'E00'),
  ('V', 'F00-F99', 'F00', 'Capítulo V - Transtornos mentais e comportamentais', 'F00', 'F00-F99', 'F00'),
  ('VI', 'G00-G99', 'G00', 'Capítulo VI - Doenças do sistema nervoso', 'G00', 'G00-G99', 'G00'),
  ('VII', 'H00-H59', 'H00', 'Capítulo VII - Doenças do olho e anexos', 'H00', 'H00-H59', 'H00'),
  ('VIII', 'H60-H95', 'H60', 'Capítulo VIII - Doenças do ouvido e da apófise mastoide', 'H60', 'H60-H95', 'H60'),
  ('IX', 'I00-I99', 'I00', 'Capítulo IX - Doenças do aparelho circulatório', 'I00', 'I00-I99', 'I00'),
  ('X', 'J00-J99', 'J00', 'Capítulo X - Doenças do aparelho respiratório', 'J00', 'J00-J99', 'J00'),
  ('XI', 'K00-K93', 'K00', 'Capítulo XI - Doenças do aparelho digestivo', 'K00', 'K00-K93', 'K00'),
  ('XII', 'L00-L99', 'L00', 'Capítulo XII - Doenças da pele e do tecido subcutâneo', 'L00', 'L00-L99', 'L00'),
  ('XIII', 'M00-M99', 'M00', 'Capítulo XIII - Doenças do sistema osteomuscular e do tecido conjuntivo', 'M00', 'M00-M99', 'M00'),
  ('XIV', 'N00-N99', 'N00', 'Capítulo XIV - Doenças do aparelho geniturinário', 'N00', 'N00-N99', 'N00'),
  ('XV', 'O00-O99', 'O00', 'Capítulo XV - Gravidez, parto e puerpério', 'O00', 'O00-O99', 'O00'),
  ('XVI', 'P00-P96', 'P00', 'Capítulo XVI - Algumas afecções originadas no período perinatal', 'P00', 'P00-P96', 'P00'),
  ('XVII', 'Q00-Q99', 'Q00', 'Capítulo XVII - Malformações congênitas, deformidades e anomalias cromossômicas', 'Q00', 'Q00-Q99', 'Q00'),
  ('XVIII', 'R00-R99', 'R00', 'Capítulo XVIII - Sintomas, sinais e achados anormais de exames clínicos e de laboratório, não classificados em outra parte', 'R00', 'R00-R99', 'R00'),
  ('XIX', 'S00-T98', 'S00', 'Capítulo XIX - Lesões, envenenamento e algumas outras consequências de causas externas', 'S00', 'S00-T98', 'S00'),
  ('XX', 'V01-Y98', 'V01', 'Capítulo XX - Causas externas de morbidade e de mortalidade', 'V01', 'V01-Y98', 'V01'),
  ('XXI', 'Z00-Z99', 'Z00', 'Capítulo XXI - Fatores que influenciam o estado de saúde e o contato com os serviços de saúde', 'Z00', 'Z00-Z99', 'Z00'),
  ('XXII', 'U04-U99', 'U04', 'Capítulo XXII - Códigos para propósitos especiais', 'U04', 'U04-U99', 'U04');
