-- Criação das tabelas necessárias para setores, agentes de risco e vínculos

-- Tabela de setores
create table if not exists public.sectors (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Tabela de agentes de risco ocupacional
create table if not exists public.occupational_risk_agents (
  id bigint generated by default as identity primary key,
  codigo_tabela24 text not null,
  agente text not null,
  tipo text not null,
  descricao text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Tabela de perigos por setor (relacionamento N:N)
create table if not exists public.sector_risks (
  id bigint generated by default as identity primary key,
  sector_id bigint references public.sectors(id) on delete cascade,
  risk_agent_id bigint references public.occupational_risk_agents(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Permissões básicas
alter table public.sector_risks enable row level security;
alter table public.sectors enable row level security;
create policy "Allow insert for all" on public.sectors for insert with check (true);
create policy "Allow select for all" on public.sectors for select using (true);
alter table public.occupational_risk_agents enable row level security;
create policy "Allow insert for all" on public.occupational_risk_agents for insert with check (true);
create policy "Allow select for all" on public.occupational_risk_agents for select using (true);
alter table public.sector_risks enable row level security;
create policy "Allow insert for all" on public.sector_risks for insert with check (true);
create policy "Allow select for all" on public.sector_risks for select using (true);

-- Popule setores
insert into public.sectors (nome, descricao) values
  ('Administrativo', 'Setor administrativo'),
  ('Produção', 'Setor de produção'),
  ('Manutenção', 'Setor de manutenção');

-- Popule agentes de risco (exemplo)
insert into public.occupational_risk_agents (codigo_tabela24, agente, tipo, descricao) values
  ('01.01.001', 'Máquina Rotativa', 'Físico', 'Equipamento com partes móveis'),
  ('01.02.002', 'Produto Químico', 'Químico', 'Substância perigosa'),
  ('01.03.003', 'Queda de Altura', 'Acidente', 'Risco de queda em altura');

-- Relacione setores e agentes de risco
insert into public.sector_risks (sector_id, risk_agent_id) values
  (1, 1), -- Administrativo - Máquina Rotativa
  (2, 2), -- Produção - Produto Químico
  (3, 3); -- Manutenção - Queda de Altura
