-- Tabela de EPI/EPC
create table if not exists public.epi_epc (
  id bigint generated by default as identity primary key,
  nome text not null,
  tipo text not null, -- 'EPI' ou 'EPC'
  ca text, -- Certificado de Aprovação
  validade_ca date,
  fabricante text,
  estoque integer default 0,
  periodicidade_troca integer, -- em meses
  created_at timestamp with time zone default timezone('utc', now())
);

-- Tabela de entregas de EPI/EPC
create table if not exists public.entrega_epi_epc (
  id bigint generated by default as identity primary key,
  id_epi_epc bigint references public.epi_epc(id) on delete cascade,
  id_funcionario bigint references public.funcionario(id_sst) on delete cascade,
  id_risco bigint references public.risco(id), -- novo campo: risco do PGR vinculado à entrega
  data_entrega date not null default now(),
  quantidade integer not null,
  termo_assinado boolean default false,
  validade date, -- validade do EPI/EPC entregue
  created_at timestamp with time zone default timezone('utc', now())
);

-- Tabela de relacionamento EPI/EPC <-> Risco (PGR)
create table if not exists public.epi_epc_risco (
  id bigint generated by default as identity primary key,
  id_epi_epc bigint references public.epi_epc(id) on delete cascade,
  id_risco bigint references public.risco(id) on delete cascade
);

-- Permissões básicas
alter table public.epi_epc enable row level security;
create policy "Allow insert for all" on public.epi_epc for insert with check (true);
create policy "Allow select for all" on public.epi_epc for select using (true);
alter table public.entrega_epi_epc enable row level security;
create policy "Allow insert for all" on public.entrega_epi_epc for insert with check (true);
create policy "Allow select for all" on public.entrega_epi_epc for select using (true);
