-- Tabela de fornecedores/terceiros
create table if not exists public.fornecedores (
  id bigint generated by default as identity primary key,
  nome text not null,
  cnpj text,
  contato text,
  responsavel_sst text,
  email text,
  telefone text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Tabela de documentos de fornecedores
create table if not exists public.documentos_fornecedor (
  id bigint generated by default as identity primary key,
  id_fornecedor bigint references public.fornecedores(id) on delete cascade,
  tipo text not null, -- contrato, PCMSO, PGR, ASO, etc.
  arquivo_url text,
  validade date,
  status text, -- válido, pendente, vencido
  observacao text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Tabela de trabalhadores terceirizados
create table if not exists public.trabalhadores_terceiros (
  id bigint generated by default as identity primary key,
  id_fornecedor bigint references public.fornecedores(id) on delete cascade,
  nome text not null,
  cpf text,
  funcao text,
  treinamentos text, -- lista ou referência
  exames text, -- lista ou referência
  created_at timestamp with time zone default timezone('utc', now())
);

-- Permissões básicas
alter table public.fornecedores enable row level security;
create policy "Allow insert for all" on public.fornecedores for insert with check (true);
create policy "Allow select for all" on public.fornecedores for select using (true);
alter table public.documentos_fornecedor enable row level security;
create policy "Allow insert for all" on public.documentos_fornecedor for insert with check (true);
create policy "Allow select for all" on public.documentos_fornecedor for select using (true);
alter table public.trabalhadores_terceiros enable row level security;
create policy "Allow insert for all" on public.trabalhadores_terceiros for insert with check (true);
create policy "Allow select for all" on public.trabalhadores_terceiros for select using (true);
