-- Tabela para acidentes de trabalho (S-2210/CAT)
create table if not exists public.occupational_accidents (
  id bigint generated by default as identity primary key,
  cpf text not null,
  nome text not null,
  setor text not null,
  data_acidente date not null,
  descricao text not null,
  agente_causador text,
  cid text,
  diagnostico text,
  user_id uuid,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Permissões básicas para leitura e inserção
alter table public.occupational_accidents enable row level security;
create policy "Allow insert for all" on public.occupational_accidents for insert with check (true);
create policy "Allow select for all" on public.occupational_accidents for select using (true);
