-- Tabela de programas e laudos adicionais
create table if not exists public.programas_laudos (
  id bigint generated by default as identity primary key,
  tipo text not null, -- LTCAT, PPP, PCA, PPR, etc.
  nome text not null,
  setor text,
  funcao text,
  funcionario bigint references public.funcionario(id_sst),
  arquivo_url text,
  validade date,
  revisao integer,
  status text, -- vigente, vencido, em revisão
  observacao text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Tabela de revisões de laudos
create table if not exists public.revisoes_laudos (
  id bigint generated by default as identity primary key,
  id_laudo bigint references public.programas_laudos(id) on delete cascade,
  data_revisao date not null,
  responsavel text,
  arquivo_url text,
  observacao text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Permissões básicas
alter table public.programas_laudos enable row level security;
create policy "Allow insert for all" on public.programas_laudos for insert with check (true);
create policy "Allow select for all" on public.programas_laudos for select using (true);
alter table public.revisoes_laudos enable row level security;
create policy "Allow insert for all" on public.revisoes_laudos for insert with check (true);
create policy "Allow select for all" on public.revisoes_laudos for select using (true);
