-- Tabela de setores para vincular perigos e acidentes
create table if not exists public.sectors (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Tabela de perigos por setor (relacionamento N:N)
create table if not exists public.sector_risks (
  id bigint generated by default as identity primary key,
  sector_id bigint references public.sectors(id) on delete cascade,
  risk_agent_id bigint references public.occupational_risk_agents(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Permissões básicas
alter table public.sectors enable row level security;
create policy "Allow insert for all" on public.sectors for insert with check (true);
create policy "Allow select for all" on public.sectors for select using (true);
alter table public.sector_risks enable row level security;
create policy "Allow insert for all" on public.sector_risks for insert with check (true);
create policy "Allow select for all" on public.sector_risks for select using (true);
