-- Tabela para documentos versionados (inventário, plano de ação, etc)
create table if not exists public.versioned_documents (
  id bigint generated by default as identity primary key,
  doc_type text not null, -- inventario, plano_acao, emergencia, etc
  title text not null,
  description text,
  file_url text not null,
  version integer not null,
  created_by text,
  created_at timestamp with time zone default timezone('utc', now())
);

alter table public.versioned_documents enable row level security;
create policy "Allow insert for all" on public.versioned_documents for insert using (true);
create policy "Allow select for all" on public.versioned_documents for select using (true);
