-- Tabela para relatos psicossociais (canal de denúncia/sugestão)
create table if not exists public.psychosocial_reports (
  id bigint generated by default as identity primary key,
  tipo text not null,
  mensagem text not null,
  anonimo boolean default true,
  user_id uuid,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Permissões básicas para leitura e inserção
alter table public.psychosocial_reports enable row level security;
create policy "Allow insert for all" on public.psychosocial_reports for insert with check (true);
create policy "Allow select for all" on public.psychosocial_reports for select using (true);
