-- Tabela para absenteísmo (faltas dos colaboradores)
create table if not exists public.absenteeism (
  id bigint generated by default as identity primary key,
  user_id uuid,
  data_falta date not null,
  motivo text,
  setor text,
  created_at timestamp with time zone default timezone('utc', now())
);

alter table public.absenteeism enable row level security;
create policy "Allow insert for all" on public.absenteeism for insert with check (true);
create policy "Allow select for all" on public.absenteeism for select using (true);
