-- Tabela para agentes de risco ocupacionais (compatível S-2240)
create table if not exists public.occupational_risk_agents (
  id bigint generated by default as identity primary key,
  codigo_tabela24 text not null, -- Código do agente na Tabela 24 do eSocial
  agente text not null,          -- Nome do agente
  tipo text not null,            -- Físico, Químico, Biológico, Ergonômico, etc.
  descricao text,                -- Descrição detalhada
  nr text,                       -- Norma Regulamentadora relacionada
  setor text,                    -- Setor/área de exposição
  epi text,                      -- EPI utilizado
  ca_epi text,                   -- CA do EPI
  epc text,                      -- EPC utilizado
  intensidade text,              -- Intensidade/Concentração
  tecnica_avaliacao text,        -- Técnica de avaliação (ex: dosimetria, laudo, etc.)
  data_avaliacao date,           -- Data da avaliação
  responsavel_avaliacao text,    -- Responsável técnico
  created_at timestamp with time zone default timezone('utc', now())
);

alter table public.occupational_risk_agents enable row level security;
create policy "Allow insert for all" on public.occupational_risk_agents for insert with check (true);
create policy "Allow select for all" on public.occupational_risk_agents for select using (true);
