-- Tabela de logs de ações sobre documentos digitais (rastreabilidade)
create table if not exists public.document_logs (
  id bigint generated by default as identity primary key,
  action text not null, -- upload, consulta, etc
  file text not null,
  user text,
  timestamp timestamptz not null
);

alter table public.document_logs enable row level security;
create policy "Allow insert for all" on public.document_logs for insert with check (true);
create policy "Allow select for all" on public.document_logs for select using (true);
