-- Tabela para respostas do questionário psicossocial, separando identidade da resposta técnica
create table if not exists public.psychosocial_questionnaire_responses (
  id bigint generated by default as identity primary key,
  setor text not null,
  resposta jsonb not null,
  anonimo boolean default true,
  user_id uuid,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Permissões básicas para leitura e inserção
alter table public.psychosocial_questionnaire_responses enable row level security;
create policy "Allow insert for all" on public.psychosocial_questionnaire_responses for insert with check (true);
create policy "Allow select for all" on public.psychosocial_questionnaire_responses for select using (true);

-- View para garantir anonimato e agregação por setor (mínimo 5 respostas)
create or replace view public.psychosocial_questionnaire_aggregated as
select setor, count(*) as total_respostas, jsonb_agg(resposta) as respostas
from public.psychosocial_questionnaire_responses
where anonimo = true or user_id is null
  group by setor
having count(*) >= 5;

-- Exemplo de trigger para garantir que user_id não seja gravado se anonimo = true
create or replace function public.ensure_anonymous_response()
returns trigger as $$
begin
  if NEW.anonimo then
    NEW.user_id := null;
  end if;
  return NEW;
end;
$$ language plpgsql;

create trigger ensure_anonymous_response_trigger
before insert on public.psychosocial_questionnaire_responses
for each row execute procedure public.ensure_anonymous_response();
