-- Tabela para registro de levantamentos preliminares de perigos e riscos
create table if not exists public.preliminary_hazard_assessment (
  id bigint generated by default as identity primary key,
  context text not null,
  hazard text not null,
  risk text not null,
  immediate_action text,
  cannot_eliminate boolean default false,
  created_at timestamp with time zone default timezone('utc', now())
);

alter table public.preliminary_hazard_assessment enable row level security;
create policy "Allow insert for all" on public.preliminary_hazard_assessment for insert using (true);
create policy "Allow select for all" on public.preliminary_hazard_assessment for select using (true);
