-- Tabela para turnover (demissões e admissões)
create table if not exists public.turnover (
  id bigint generated by default as identity primary key,
  user_id uuid,
  tipo text not null, -- 'admissao' ou 'demissao'
  data_evento date not null,
  setor text,
  motivo text,
  created_at timestamp with time zone default timezone('utc', now())
);

alter table public.turnover enable row level security;
create policy "Allow insert for all" on public.turnover for insert with check (true);
create policy "Allow select for all" on public.turnover for select using (true);
