-- Tabela para quase acidentes (near misses)
create table if not exists public.near_misses (
  id bigint generated by default as identity primary key,
  user_id uuid,
  setor text,
  descricao text,
  data_evento date not null,
  created_at timestamp with time zone default timezone('utc', now())
);

alter table public.near_misses enable row level security;
create policy "Allow insert for all" on public.near_misses for insert with check (true);
create policy "Allow select for all" on public.near_misses for select using (true);
