-- Criação da tabela de medidas de prevenção do plano de ação
create table if not exists public.action_plan_measures (
  id bigint generated by default as identity primary key,
  measure_name text not null,
  description text,
  responsible text,
  due_date date,
  trabalhadores_expostos integer default 0,
  created_at timestamp with time zone default timezone('utc', now()),
  notified boolean default false
);

-- Permissões básicas para leitura e inserção
alter table public.action_plan_measures enable row level security;
create policy "Allow insert for all" on public.action_plan_measures for insert using (true);
create policy "Allow select for all" on public.action_plan_measures for select using (true);
