-- Tabela para exames ocupacionais (ASO) vinculados ao trabalhador e riscos monitorados
create table if not exists public.occupational_exams (
  id bigint generated by default as identity primary key,
  cpf_trabalhador text not null,
  nome_trabalhador text not null,
  tipo_exame text not null, -- Admissional, Periódico, Demissional, etc.
  data_exame date not null,
  resultado text not null, -- Apto, Inapto, etc.
  riscos_exame jsonb not null, -- Lista de códigos Tabela 24 dos riscos monitorados neste exame
  riscos_inventario jsonb, -- Lista de códigos Tabela 24 dos riscos ativos no S-2240 para este trabalhador (preenchido na validação)
  validado boolean default false, -- Se a validação cruzada foi feita
  inconsistencias text, -- Descrição de inconsistências, se houver
  created_at timestamp with time zone default timezone('utc', now())
);

alter table public.occupational_exams enable row level security;
create policy "Allow insert for all" on public.occupational_exams for insert with check (true);
create policy "Allow select for all" on public.occupational_exams for select using (true);
