-- Tabela para planos de emergência e simulações
create table if not exists public.emergency_plans (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  responsible text,
  resources text,
  simulation_date date,
  evidence_url text,
  created_at timestamp with time zone default timezone('utc', now())
);

alter table public.emergency_plans enable row level security;
create policy "Allow insert for all" on public.emergency_plans for insert using (true);
create policy "Allow select for all" on public.emergency_plans for select using (true);
