-- Criação da tabela para percepções de risco dos trabalhadores
create table if not exists public.risk_perceptions (
  id bigint generated by default as identity primary key,
  name text,
  perception text not null,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Permissões básicas para leitura e inserção
alter table public.risk_perceptions enable row level security;
create policy "Allow insert for all" on public.risk_perceptions for insert using (true);
create policy "Allow select for all" on public.risk_perceptions for select using (true);
