-- Tabela para lembretes/revisões periódicas de riscos
create table if not exists public.risk_review_reminders (
  id bigint generated by default as identity primary key,
  risk_id bigint not null,
  due_date date not null,
  notified boolean default false,
  created_at timestamp with time zone default timezone('utc', now())
);

alter table public.risk_review_reminders enable row level security;
create policy "Allow insert for all" on public.risk_review_reminders for insert using (true);
create policy "Allow select for all" on public.risk_review_reminders for select using (true);
